version: '3.8'

services:
  # Frontend service
  frontend:
    build: ./frontend
    ports:
      - "3050:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_RUNTIME_ENV=docker
    depends_on:
      - api
    networks:
      - kidsask-network

  # API Gateway service
  api:
    build: ./api
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - ai-service
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=27017
      - DB_NAME=kidsaskdb
      - AI_SERVICE_URL=http://ai-service:5050
    networks:
      - kidsask-network

  # AI Service for processing questions
  ai-service:
    build: ./ai-service
    ports:
      - "5050:5050"
    volumes:
      - ./ai-service:/app
    environment:
      - AI_MODEL_CONFIG_PATH=/app/config/model_config.json
    networks:
      - kidsask-network

  # MongoDB Database
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - kidsask-network

networks:
  kidsask-network:
    driver: bridge

volumes:
  mongodb_data:
