version: '3.8'

services:
  # Frontend service
  frontend:
    build: ./frontend
    ports:
      - "3050:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_RUNTIME_ENV=docker
    depends_on:
      - api
    networks:
      - kidsask-network

  # API Gateway service
  api:
    build: ./api
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - ai-service
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=27017
      - DB_NAME=kidsaskdb
      - AI_SERVICE_URL=http://ai-service:5050
    networks:
      - kidsask-network

  # AI Service for processing questions
  ai-service:
    build: ./ai-service
    ports:
      - "5050:5050"
    volumes:
      - ./ai-service:/app
    environment:
      - AI_MODEL_CONFIG_PATH=/app/config/model_config.json
<<<<<<< HEAD
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=tinyllama
    depends_on:
      - ollama
=======
      - OLLAMA_API_HOST=http://ollama:11434
      - OLLAMA_MODEL=gemma:2b
    depends_on:
      - ollama
    networks:
      - kidsask-network
      
  # Ollama Service for AI models
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
>>>>>>> ai-branch-new-container
    networks:
      - kidsask-network

  # MongoDB Database
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - kidsask-network
      
  # Ollama LLM service
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - kidsask-network
    restart: unless-stopped

networks:
  kidsask-network:
    driver: bridge

volumes:
  mongodb_data:
  ollama_data:
